import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import { LoginForm } from '../src/components/LoginForm';
import { useGetSession } from '../src/hooks/useUserSession';

const Home: NextPage = () => {
  const { error, status } = useGetSession();
  return (
    <div className="container flex h-full min-h-screen content-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {error && (
        <div>
          {error}-{status}
        </div>
      )}
      <LoginForm />
    </div>
  );
};

export default Home;
